[window]
startup_mode = "Fullscreen"
dynamic_padding = true
# resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 18.25

[terminal]
osc52 = "CopyPaste"
